# docker-compose.yml
version: "3"
services:
  composer:
    image: composer:2.6.6
    volumes:
      - .:/app
    restart: never
  phpunit:
    image: php:8.3-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit --testdox
